name: Compile and release


on: 
  workflow_dispatch: 
    inputs: 
      version: 
        description: "Release version (e.g. 1.0.3)"   # {{ inputs.version }}
        required: true
#  push: 
#    tags: 
#      - "v*.*.*"


jobs: 
  build: 
    runs-on: windows-latest
    steps: 

      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          ref: main

      - name: Get AutoHotKey with upx and mpress
        run: powershell curl -o ahk.zip https://github.com/SherkeyXD/ArknightsWsaHotkey/releases/download/v0.1.0/AutoHotKey_1.1.34.03_with_upx_and_mpress.zip

      - name: Unzip AutoHotKey
        run: 7z x ahk.zip -oahk/

      - name: Compile ahk to exe
        run: |
          ahk/Ahk2Exe.exe /in arknights.ahk /out wsarknights_x64.exe /icon icon.ico /compress 2 /base ahk/Unicode_64-bit.bin
          ahk/Ahk2Exe.exe /in arknights.ahk /out wsarknights_x32.exe /icon icon.ico /compress 2 /base ahk/Unicode_32-bit.bin

      - name: Release and upload files
        uses: softprops/action-gh-release@v0.1.14
#        if: startsWith(github.ref, 'refs/tags/')
        with: 
          files: |
            wsarknights_x64.exe
            wsarknights_x32.exe
          tag_name: v${{ inputs.version }}  #or {{ inputs.tags }}
          token: ${{ secrets.GITHUB_TOKEN }}
